openshift/ingress-node-firewall

ingress-nodefw-xdp/src/ingress_node_firewall_kernel.c, ingress-nodefw-xdp/src/ingress_node_firewall_stats.c
=> Ingress nodefw stats loaded using Cilium ebpf lib

ingress-nodefw-xdp/src/ingress_node_firewall_kernel.c, ingress-nodefw-xdp/src/ingress_node_firewall_loader.go
place holder for ingress node fw rules loader
=> initial template for ingress node fw rules loader

Makefile
Added makefile build rule for eBPF
=> Add make rule to build eBPF kernel and loaders.

bpf/ingress_node_firewall.h, bpf/ingress_node_firewall_kernel.c
=> add ingress node header for all structure definitions

bpf/ingress_node_firewall.h, pkg/ebpf/bpf_bpfeb.go, pkg/ebpf/bpf_bpfel.go, pkg/ebpf/ingress_node_firewall_loader.go, pkg/ebpf/ingress_node_firewall_stats.go
=> update go types

api/v1alpha1/ingressnodefirewall_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/ingress-nodefw.ingress-nodefw_ingressnodefirewalls.yaml, controllers/ingressnodefirewall_controller.go
=> minor api cleanup based on enhancement review comments

Dockerfile.openshift
the release CI is failing with
go: inconsistent vendoring in /workspace
=> Sync the vendor directory

Dockerfile.openshift
=> Fix vendor package issue by copying the vendor directory

.gitignore
That unfortunately won't prune the 60 mb from the repo, but at least it'll prevent that from happening in the future
=> Remove binaries from bin/ and fix .gitignore

Makefile
=> Add cert manager installation to makefile

Makefile, controllers/suite_test.go, hack/common.sh, hack/lint.sh, hack/self_signed_cert.yaml, hack/wait_for_cert_manager.sh, pkg/ebpf/ingress_node_firewall_loader.go
- add make lint target and fix a couple of lint errors
- cert-manager wait for ready script
=> Add wait during deploy to wait for cert manager to be installed

Makefile, README.md, bindata/manifests/daemon/daemonset.yaml, go.mod, go.sum, test/README.md, test/consts/const.go, test/e2e/client/client.go, test/e2e/functional/e2e_test.go, test/e2e/functional/tests/e2e.go, test/e2e/ingress-node-firewall/ingress-node-firewall.go, test/e2e/k8sreporter/reporter.go, test/e2e/namespaces/namespaces.go, test/e2e/validation/tests/validation.go, test/e2e/validation/validation_test.go, vendor/github.com/golang/glog/LICENSE, vendor/github.com/golang/glog/README.md, vendor/github.com/golang/glog/glog.go, vendor/github.com/golang/glog/glog_file.go, vendor/github.com/kennygrant/sanitize/.gitignore, vendor/github.com/kennygrant/sanitize/.travis.yml, vendor/github.com/kennygrant/sanitize/LICENSE, vendor/github.com/kennygrant/sanitize/README.md, vendor/github.com/kennygrant/sanitize/sanitize.go, vendor/modules.txt
- make sure all CRDs are installed
- make sure operator deployment is running
- make sure DaemonSet is running 
- Apply firewall rules and check actions 
```
=== RUN   TestE2E
Running Suite: Ingress Node Firewall Operator E2E Suite
=======================================================
Random Seed: 1659295187
Will run 1 of 1 specs
Ingress Node Firewall IngressNodeFirewall deploy 
should run Ingress node firewall
/home/mmahmoud/go/src/ingress-node-firewall/test/e2e/functional/tests/e2e.go:61
STEP: checking Ingress node firewall daemonset is in running state
STEP: get nodes IPv4 with matching labels and ping their IPs
STEP: creating ingress node firewall rules
STEP: checking Ingress node firewall rules resource is created
STEP: checking ingress node firewall node list resources is created …
```
=> basic E2E frame work for ingress node firewall

bpf/ingress_node_firewall_kernel.c
=> fix bad fmt in previous PR

pkg/webhook/webhook.go, pkg/webhook/webhook_suite_test.go, test/e2e/functional/tests/e2e.go, test/e2e/ingress-node-firewall/ingress-node-firewall.go
=> Webhook: add e2e tests

pkg/webhook/webhook.go, pkg/webhook/webhook_suite_test.go
=> Webhook: do not allow overlapping sourceCIDR and rules order

Makefile
For all tests, run:
`make test-e2e`
To narrow down the scope, run e.g.:
`make test-e2e WHAT="should run Ingress node firewall apply rules and check the actions"`
=> Add WHAT=<expression> to test-e2e

pkg/ebpf/ingress_node_firewall_loader.go
- handle multiple attach to the same interface
- make sure to unpin link and remove pinPath once objs are deleted
=> Handle XDP attach "device or resource busy" error

Makefile, README.md, bundle.Dockerfile, bundle/manifests/ingress-node-firewall-controller-manager-metrics_v1_service.yaml, bundle/manifests/ingress-node-firewall-daemon-clusterrole-binding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, bundle/manifests/ingress-node-firewall-daemon-clusterrole-extra_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/ingress-node-firewall-daemon-metrics_v1_service.yaml, bundle/manifests/ingress-node-firewall-daemon-role-binding_rbac.authorization.k8s.io_v1_rolebinding.yaml, bundle/manifests/ingress-node-firewall-daemon-role-extra_rbac.authorization.k8s.io_v1_role.yaml, bundle/manifests/ingress-node-firewall-daemon_monitoring.coreos.com_v1_servicemonitor.yaml, bundle/manifests/ingress-node-firewall-daemon_v1_serviceaccount.yaml, bundle/manifests/ingress-node-firewall-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, bundle/manifests/ingress-node-firewall-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, bundle/manifests/ingress-node-firewall-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, bundle/manifests/ingress-node-firewall-webhook-service_v1_service.yaml, bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml, bundle/manifests/ingressnodefirewall.openshift.io_ingressnodefirewallconfigs.yaml, bundle/manifests/ingressnodefirewall.openshift.io_ingressnodefirewallnodestates.yaml, bundle/manifests/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml, config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml, config/manifests/kustomization.yaml
Make rules and Bundle dockerfile to build OCP operator
=> Initial Ingress node bundle creation

Makefile
=> fix go get controller-gen issue

bundle/manifests/ingressnodefirewall.openshift.io_ingressnodefirewallnodestates.yaml, pkg/interfaces/interfaces.go, pkg/interfaces/interfaces_test.go
=> API to list all interfaces with XDP prog attached

Makefile
This reverts commit 3d2ce73f7317a9e39707d2d7ba6e47141ed86304.
Fix #107
=> Revert "fix go get controller-gen issue"

pkg/ebpf/ingress_node_firewall_loader.go, pkg/ebpf/ingress_node_firewall_loader_test.go, pkg/ebpfsyncer/ebpfsyncer.go, pkg/ebpfsyncer/ebpfsyncer_test.go, pkg/interfaces/interfaces.go
=> Make ebpfSyncer and Firewall loader idempotent for add/update/delete

Makefile
Reverts openshift/ingress-node-firewall#112
=> Revert "makefile fixes"

test/e2e/functional/tests/e2e.go, test/e2e/ingress-node-firewall/ingress-node-firewall.go, test/e2e/pods/pods.go
=> E2E: Export node interface used in E2E as var

openshift-ci/.gitignore, openshift-ci/README.md, openshift-ci/common.sh, openshift-ci/deploy_ingress_node_firewall.sh, openshift-ci/ingress-node-firewall-operator-deploy/.gitignore, openshift-ci/ingress-node-firewall-operator-deploy/build_and_push_index.sh, openshift-ci/ingress-node-firewall-operator-deploy/install-resources.yaml, openshift-ci/run_e2e.sh, openshift-ci/wait_for_csv.sh
This scripts install ingress-node-firewall into OCP, for test environment. The cluster deployment is done by dev-scripts:
https://github.com/openshift-metal3/dev-scripts
=> Add openshift-ci deployment and config files

controllers/ingressnodefirewallconfig_controller_test.go
This is a follow-up to PR #123.
=> Add "events" container to firewall config unit tests

Makefile, controllers/ingressnodefirewall_controller.go, controllers/ingressnodefirewall_controller_test.go, hack/lint.sh, pkg/ebpf/ingress_node_firewall_loader.go, pkg/ebpf/ingress_node_firewall_loader_test.go, pkg/webhook/webhook.go, pkg/webhook/webhook_suite_test.go
=> fix make lint ci job

controllers/ingressnodefirewall_controller.go, controllers/ingressnodefirewall_controller_rules_test.go
=> Avoid mutating nodeState object directly to avoid race conditions

Makefile, manifests/art.yaml, manifests/ingress-node-firewall.package.yaml, manifests/stable/ingress-node-firewall-controller-manager-metrics_v1_service.yaml, manifests/stable/ingress-node-firewall-daemon-clusterrole-binding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, manifests/stable/ingress-node-firewall-daemon-clusterrole-extra_rbac.authorization.k8s.io_v1_clusterrole.yaml, manifests/stable/ingress-node-firewall-daemon-metrics_v1_service.yaml, manifests/stable/ingress-node-firewall-daemon-role-binding_rbac.authorization.k8s.io_v1_rolebinding.yaml, manifests/stable/ingress-node-firewall-daemon-role-extra_rbac.authorization.k8s.io_v1_role.yaml, manifests/stable/ingress-node-firewall-daemon_monitoring.coreos.com_v1_servicemonitor.yaml, manifests/stable/ingress-node-firewall-daemon_v1_serviceaccount.yaml, manifests/stable/ingress-node-firewall-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, manifests/stable/ingress-node-firewall-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, manifests/stable/ingress-node-firewall-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, manifests/stable/ingress-node-firewall-webhook-service_v1_service.yaml, manifests/stable/ingress-node-firewall.clusterserviceversion.yaml, manifests/stable/ingressnodefirewall.openshift.io_ingressnodefirewallconfigs.yaml, manifests/stable/ingressnodefirewall.openshift.io_ingressnodefirewallnodestates.yaml, manifests/stable/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
=> Create manifest folder for ART to be able to build operator bundle

manifests/stable/image-references
=> Add missing image-references required by ART build

Makefile, README.md, hack/set-daemon-image.sh
=> Improvements

manifests/art.yaml
Signed-off-by: D. Paolella <dpaolell@redhat.com>
=> Fix art.yaml

pkg/metrics/statistics.go
statistics while running ping test (fix #159)
```
k exec -it -n ingress-node-firewall-system   ingress-node-firewall-daemon-f9n2d -c daemon -- bash -c "curl 127.0.0.1:39301/metrics | grep ingressnodefirewall_node_packet_"
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 16574    0 16574    0     0  15.8M      0 --:--:-- --:--:-- --:--:-- 15.8M
ingressnodefirewall_node_packet_allow_bytes 0
ingressnodefirewall_node_packet_allow_total 0
ingressnodefirewall_node_packet_deny_bytes 45570
ingressnodefirewall_node_packet_deny_total 465
```
=> use uint64 for statistics update to fix #159

Makefile, bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml, config/manager/env.yaml, config/manager/kustomization.yaml, manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
=> remove debug images name and point to ocp images

manifests/stable/image-references
Signed-off-by: D. Paolella <dpaolell@redhat.com>
=> Fix image-references

pkg/webhook/webhook.go
within the same rule order is guranteed to be unique from API definition
fix #170 
=> Order overlap check should be done between different rules

openshift-ci/deploy_ingress_node_firewall.sh
The images in he CSV are now pointing to quay.io/openshift repo. We need to fix CI deploy script to replaces them with CI builds.
=> openshift-ci: Fix CSV images

pkg/ebpfsyncer/ebpfsyncer.go
Close() function takecare of doing the detach no need to use netlink to do another detach.
Probably old problem was related to some of race
issues in the controller however if it came again
we should fix it and not doing this.
changes passed UT, e2e and ebpfsyncer ut
```sh
go test -exec sudo ./...
ok      github.com/openshift/ingress-node-firewall/pkg/ebpfsyncer       47.630s
```
manual e2e test run results
```sh
Ran 11 of 11 Specs in 175.744 seconds
SUCCESS! -- 11 Passed | 0 Failed | 0 Pending | 0 Skipped
```
=> fix doing multiple detach in ebpfsyncer

README.md, test/README.md
=> E2E tests: Add KinD IPV6 known issue to README

bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml, config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml, manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
Add suggested name space to manifest just to give users different options
=> OCPBUGS-1435: added suggest ns to manifest

Makefile, bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml, config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml, config/olm-install/install-resources.yaml, manifests/art.yaml, manifests/ingress-node-firewall.package.yaml, manifests/stable/ingress-node-firewall.clusterserviceversion.yaml, openshift-ci/wait_for_csv.sh, pkg/version/version.go
Signed-off-by: D. Paolella <dpaolell@redhat.com>
=> Bump version to 4.13

bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml, config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml, manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
=> OCPBUGS-1328: fix incorrect link field setting

bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml, config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml, manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
=> update operator image to 4.13

.github/dependabot.yml
Signed-off-by: msherif1234 <mmahmoud@redhat.com>
=> change dependabot to run weekly instead of daily

bindata/manifests/daemon/daemonset.yaml, bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml, config/manager/manager.yaml, manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
Signed-off-by: msherif1234 <mmahmoud@redhat.com>
=> OCPBUGS-6646: fix ingress node firewall ci

OWNERS
=> Fix #311 sync owners list with other openshift networking repo

openshift-ci/deploy_ingress_node_firewall.sh, test/e2e/pods/pods.go
=> E2E: fix ci issue with ncat test pods

bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml, config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
=> OCPBUGS-10936: Fix INFW operator provider name

Makefile, bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml, config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml, config/olm-install/install-resources.yaml, config/openshift/patch.yaml, manifests/art.yaml, manifests/ingress-node-firewall.package.yaml, manifests/stable/ingress-node-firewall.clusterserviceversion.yaml, openshift-ci/wait_for_csv.sh, pkg/version/version.go
=> OCPBUGS-11241: update ingressnode firewall cvs and manifest to use 4.14

bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml, config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
=> OCPBUGS-10936: fix Provider name for the operator

manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
=> OCPBUGS-10936: fixing missing string in manifest

pkg/ebpf/ingress_node_firewall_loader.go, pkg/interfaces/interfaces.go, pkg/interfaces/interfaces_test.go
with running rhel9 we have now bond XDP native support by design xdp packets will be carrying member interface index not the bond interface, while we still only
attach to bond interface
Fix XDP on bond interface with rhel9 where it brings in native XDP driver
- bring up OCP cluster with the changes
- verify keys have the member interface index instead of the bond
```bash
5: packet0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP mode DEFAULT group default qlen 1000
link/ether 50:7c:6f:13:cc:92 brd ff:ff:ff:ff:ff:ff
altname enp1s0f0
6: packet1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP mode DEFAULT group default qlen …
```
=> OCPBUGS-11885: use bond members as keys instead of bond interface

Makefile
=> use cilium v0.11.0

Dockerfile.daemon.openshift, Dockerfile.openshift, Makefile, bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml, config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml, config/olm-install/install-resources.yaml, config/openshift-olm/kustomization.yaml, manifests/art.yaml, manifests/ingress-node-firewall.package.yaml, manifests/stable/ingress-node-firewall.clusterserviceversion.yaml, openshift-ci/wait_for_csv.sh, pkg/version/version.go
Update node firewall to `4.15` branch
=> Update ingress-node-firewall to 4.15 release

main.go
ingress node firewall operator remediation for CVE-2023-44487
=> OCPBUGS-20654: Modify controller-runtime to disable HTTP/2 for metrics and webhook

main.go
ingress node firewall operator remediation for CVE-2023-44487
=> OCPBUGS-20638: Modify controller-runtime to disable HTTP/2 (4.12)

bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml, config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml, manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
update operator image in the csv
=> OCPBUGS-22756: update manifset operator image

bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml, config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml, manifests/stable/ingress-node-firewall.clusterserviceversion.yaml, openshift-ci/common.sh
=> OCPBUGS-30623: Set infra labels in ingress-node-firewall-operator

bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml, config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml, manifests/stable/ingress-node-firewall.clusterserviceversion.yaml, openshift-ci/common.sh
=> OCPBUGS-30626: Set infra labels in ingress-node-firewall-operator

bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml, config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
remove usage of replace from all CSV definition
=> remove replace from CSV

pkg/bpf-mgr/lib-bpfman.go
The following e2e test case was failing because bpfapplication wasn't updated correctly now with the fix it pass
```shell
WHAT="non existent interface name in unrelated IngressNodeFirewall doesn't block application of new IngressNodeFirewalls policies" make test-e2e 
/home/mmahmoud/go/src/ingress-node-firewall/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
==== Generating DaemonSet manifest
hack/generate-daemon-manifest.sh
/home/mmahmoud/go/src/ingress-node-firewall/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
cp bundle/manifests/* manifests/stable
rm -rf /tmp/test_validation_logs/
mkdir -p /tmp/test_validation_logs/ …
```
=> fix update bpfapplication object

go.mod, go.sum, vendor/github.com/golang/glog/glog.go, vendor/github.com/golang/glog/glog_file.go, vendor/github.com/golang/glog/glog_file_nonwindows.go, vendor/github.com/golang/glog/glog_file_windows.go, vendor/modules.txt
=> [Release-4.16] OCPBUGS-58573: bump github.com/golang/glog-1.2.1 to 1.2.4

go.mod, go.sum, vendor/github.com/golang/glog/glog.go, vendor/github.com/golang/glog/glog_file.go, vendor/github.com/golang/glog/glog_file_nonwindows.go, vendor/github.com/golang/glog/glog_file_windows.go, vendor/modules.txt
=> [Release-4.15] OCPBUGS-58578: bump github.com/golang/glog-1.2.0 to 1.2.4
