Dockerfile.openshift

Creating basic OCP dockerfile to enable openshift-ci bot functionality for this repo
and unblock [PR#30687](https://github.com/openshift/release/pull/30687)

Add Dockerfile for OCP to enable release CI process PR# 30687

---

Makefile

BPF_CLANG and BPF_CLANGS should be set for ebpf-generate.
That way, the ebpf-generate target can be called by itself,
without the generate target.

Fix variable in Makefile for ebpf-generate

---

.gitignore
Makefile
README.md
hack/kind-cluster.sh

Put kind kubeconfig into its own location and add worker node label.
Add Makefile targets for kind deployment and deletion.

Update kind hack script

---

config/default/manager_auth_proxy_patch.yaml

If the manager process is to listen to webhooks then we must add this in
the manager_auth_proxy_patch.
We unfortunately can't append this via manager_webhook_patch.yaml as
this would lead to a merge conflict.

Append --enable-webhook to manager

---

bindata/manifests/daemon/daemonset.yaml
pkg/ebpf/ingress_node_firewall_events.go

This file can be collected by must-gather with pods logs
to help debugging
```
k exec -t  -n ingress-node-firewall-system   ingress-node-firewall-daemon-5djbd -c daemon -- cat /tmp/ingress_node_firewall_events.log
2022/08/01 17:28:37 ========= Drop Event ===========
2022/08/01 17:28:37     ruleId 10 action Drop len 98
2022/08/01 17:28:37     ipv4 src addr 172.18.0.1 dst addr 172.18.0.2
2022/08/01 17:28:37     icmpv4 type 8 code 0
2022/08/01 17:28:38 ========= Drop Event ===========
2022/08/01 17:28:38     ruleId 10 action Drop len 98
2022/08/01 17:28:38     ipv4 src addr 172.18.0.1 dst addr 172.18.0.2
2022/08/01 17:28:38     icmpv4 type 8 code 0
2022/08/01 17:28:39 ========= Drop Event ===========
2022/08/01 17:28:39     ruleId 10 action Drop len 98
2022/08/01 17:28:39     ipv4 src addr …
```

Log eBPF events packet's logs to a file

---

pkg/failsaferules/failsaferules.go

BPF was dropping mDNS UDP packets on port 5353
```
2022/08/01 17:29:29 ========= Drop Event ===========
2022/08/01 17:29:29     ruleId 0 action Drop len 81
2022/08/01 17:29:29     ipv4 src addr 172.18.0.1 dst addr 224.0.0.251
2022/08/01 17:29:29     udp srcPort 5353 dstPort 5353
```

Add Multicast DNS port 5353 to UDP's failsafe rules

---

test/consts/const.go
test/e2e/functional/tests/e2e.go
test/e2e/ingress-node-firewall/ingress-node-firewall.go

```
Ingress Node Firewall IngressNodeFirewall deploy 
should run Ingress node firewall apply rules and check the actions
/home/mmahmoud/go/src/ingress-node-firewall/test/e2e/functional/tests/e2e.go:92
STEP: get nodes IP addresses with matching labels and ping their IPs
STEP: creating ingress node firewall rules
STEP: checking Ingress node firewall rules resource is created
STEP: checking ingress node firewall nodeState resource is created
STEP: checking Ingress node firewall rules deny ping packets
STEP: checking ingress node firewall events are generated
STEP: checking Ingress node firewall nodeState resource is deleted
STEP: checking Ingress node firewall rules resource is deleted
• [SLOW TEST:32.318 seconds]
Ingress Node Firewall …
```

E2E test case to check for eBPF events generattion

---

test/e2e/client/client.go

Instead of failing later down the road with a nil pointer exception,
panic early instead.
Would this make sense?
The result will be:
~~~
[akaris@linux ingress-node-firewall (sdn-3315)]$ make test-e2e
/home/akaris/development/ingress-node-firewall/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
==== Generating DaemonSet manifest
hack/generate-daemon-manifest.sh
/home/akaris/development/ingress-node-firewall/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
rm -rf /tmp/test_validation_logs/
mkdir -p /tmp/test_validation_logs/
go test --tags=validationtests -v ./test/e2e/validation -ginkgo.v -junit …

Panic right away if kubeconfig cannot be found

---

Dockerfile.daemon.openshift
hack/build-daemon.sh

Need to have dockefile for OCP to build Daemonset image by the release team

Add OCP dockerfile to build DaemonSet.

---

.gitignore
Makefile
hack/lint.sh

It is causing issues when run unit-test from
release CI we get the following error
GOBIN=/go/src/github.com/openshift/ingress-node-firewall/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.0
25
go: sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.0: cannot query module due to -mod=vendor
26
make: *** [/go/src/github.com/openshift/ingress-node-firewall/bin/controller-gen] Error 1

change how we do envtest target and linit script to work from ci repo

---

pkg/utils/interfaces.go
pkg/utils/interfaces_test.go

before attaching XDP to interfaces we need to make
sure interfaces are valid and in the right state
fixed #91 

Interfaces validation pkg

---

controllers/ingressnodefirewall_controller.go
controllers/ingressnodefirewall_controller_test.go
pkg/ebpfsyncer/ebpfsyncer.go
pkg/ebpfsyncer/ebpfsyncer_test.go
pkg/webhook/webhook.go
pkg/webhook/webhook_suite_test.go
test/e2e/functional/tests/e2e.go

Fix #99 
- allow some waiting time for rules delete to complete.
- remove webhook test cases that are now not allowed by the APIs.
here is what the API verify for us:
- for order 0 we will get this error
```
The IngressNodeFirewall "ingressnodefirewall-demo2" is invalid: spec.ingress[0].rules[0].order: Invalid value: 0: spec.ingress[0].rules[0].order in body should be greater than or equal to 1
```
- for mixed protocol case we will get
```
* spec.ingress[0][rules][0]: Invalid value: "ingressnodefirewall-demo2": must be a valid TCP rule: no port defined
* spec.ingress[0][rules][1]: Invalid value: "ingressnodefirewall-demo2": must be a valid ICMP(V6) rule: no ICMP rules defined. Define icmpType/icmpCode
```
here is fresh e2e run after cluster is created after adding the wait to make sure …

Fix initial e2e run issue #99

---

controllers/ingressnodefirewall_controller_rules_test.go
controllers/ingressnodefirewallconfig_controller_test.go
controllers/suite_test.go

Fix one of the race conditions in #93 where fwconfig was removing the namespace while fwrules and nodestate are still running.

fix one of the unit-test race condition issues

---

bindata/manifests/daemon/daemonset.yaml

Use an initContainer to mount the BPF file system. The goal here is to
separate the concerns when the daemon is started.
This would also allow us to drop the command reference (i.e.,
'/usr/bin/daemon') and rely on the entrypoint specified in the
Dockerfile.

manifests/daemonset: Use an init container to mount bpffs

---

config/openshift/namespace.yaml
controllers/ingressnodefirewallconfig_controller.go
main.go
pkg/platform/platform.go
pkg/platform/types.go
test/e2e/functional/tests/e2e.go

add pkg to detect if running on OCP cluster or not to customize securityContext
e2e was extended to check the cluster type

E2E: Add platform pkg to detect running on OCP cluster type

---

test/e2e/functional/tests/e2e.go
test/e2e/ingress-node-firewall/ingress-node-firewall.go

we need to be able to run e2e test on any cluster not KinD cluster only
- run `make test-e2e` on any cluster CIDR range should be calculated based on the nodes IPv4and IPv6 addresses.
- manual run of e2e passed on kind
```
Ran 10 of 10 Specs in 304.583 seconds
SUCCESS! -- 10 Passed | 0 Failed | 0 Pending | 0 Skipped
```
drive CIDR value for the rules from node IPv4 and IPv6 addresses

 E2E: Remove hardcode KinD's CIDR range from e2e fw rules

---

Makefile

If I run:
```console
$ make -n test
echo "==== Generating DaemonSet manifest"
hack/generate-daemon-manifest.sh
/home/aim/src/github.com/openshift/ingress-node-firewall/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/aim/src/github.com/openshift/ingress-node-firewall/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
GOBIN=/home/aim/src/github.com/openshift/ingress-node-firewall/bin
mkdir -p /home/aim/src/github.com/openshift/ingress-node-firewall/testbin
test -f /home/aim/src/github.com/openshift/ingress-node-firewall/testbin/setup-envtest.sh || curl -sSLo /home/aim/src/github.com/openshift/ingress-node-firewall/testbin/setup-envtest.sh …
```

Makefile: explicitly set KUBEBUILDER_ASSETS for test target

---

controllers/ingressnodefirewall_controller.go
pkg/ebpf/ingress_node_firewall_events.go

- fix failing ut test cases path from @andreaskaris 
- fix lint issue in the event code.
- make test
```bash
KUBEBUILDER_ASSETS="/home/mmahmoud/go/src/ingress-node-firewall/testbin/bin" go test ./... -coverprofile cover.out
?       github.com/openshift/ingress-node-firewall      [no test files]
?       github.com/openshift/ingress-node-firewall/api/v1alpha1 [no test files]
?       github.com/openshift/ingress-node-firewall/cmd/daemon   [no test files]
?       github.com/openshift/ingress-node-firewall/cmd/syslog   [no test files]
ok      github.com/openshift/ingress-node-firewall/controllers  10.645s coverage: 77.5% of statements
?       github.com/openshift/ingress-node-firewall/pkg/apply    [no test files]
ok …
```

fix rules test cases and fix a couple of lint errors

---

controllers/ingressnodefirewallconfig_controller.go
test/e2e/functional/tests/e2e.go
test/e2e/ingress-node-firewall/ingress-node-firewall.go

Passed KinD e2e test run
```
Ran 11 of 11 Specs in 382.665 seconds
SUCCESS! -- 11 Passed | 0 Failed | 0 Pending | 0 Skipped
```

E2E: allow running on single stack cluster while the  default still dualstack

---

Makefile
api/v1alpha1/groupversion_info.go
bundle/manifests/ingressnodefirewall.openshift.io_ingressnodefirewallconfigs.yaml
config/crd/bases/ingressnodefirewall.openshift.io_ingressnodefirewallconfigs.yaml
controllers/ingressnodefirewall_controller.go
controllers/ingressnodefirewallconfig_controller.go
controllers/ingressnodefirewallnodestate_controller_test.go
controllers/suite_test.go
pkg/ebpf/bpf_bpfeb.go
pkg/ebpf/bpf_bpfel.go
pkg/ebpf/ingress_node_firewall_loader.go
pkg/metrics/statistics.go
pkg/status/status.go
pkg/webhook/webhook.go

- trigger nodeState reconciler only if fwobj nodeselector match node object label
- add `make test-race` to detect race conditions.
- ran UT
- ran e2e on kind and it passed with those changes
```
Ran 11 of 11 Specs in 331.492 seconds
SUCCESS! -- 11 Passed | 0 Failed | 0 Pending | 0 Skipped
```

Trigger nodeState reconcilation only for fwobj with matching node's label

---

config/openshift/kustomization.yaml

Following the readme steps, I noticed that the ns
for OCP isn't being created.

Fix missing namespace declaration for OCP

---

Makefile
bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
config/olm-install/install-resources.yaml
manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
openshift-ci/wait_for_csv.sh
pkg/version/version.go

the logic in art.yaml wasn't able to find v0.0.1 in the daily build hence wasn't updating CSV correctly

OCPBUGS-1621: fix version to allow art build with the proper version with timestamp

---

Makefile
api/v1alpha1/ingressnodefirewall_types.go
bundle/manifests/ingressnodefirewall.openshift.io_ingressnodefirewallnodestates.yaml
bundle/manifests/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
config/crd/bases/ingressnodefirewall.openshift.io_ingressnodefirewallnodestates.yaml
config/crd/bases/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
hack/kind-cluster.sh
manifests/stable/ingressnodefirewall.openshift.io_ingressnodefirewallnodestates.yaml
manifests/stable/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
pkg/webhook/webhook.go
pkg/webhook/webhook_suite_test.go

webhhok ICMP and ICMPv6 check was missing
for more details refer to issue #205
manual e2e run results
```
Ran 11 of 11 Specs in 168.696 seconds
SUCCESS! -- 11 Passed | 0 Failed | 0 Pending | 0 Skipped
```

OCPBUGS-2316: Mixing ICMP v4 and v6 config causes a panic

---

test/e2e/exec/exec.go
test/e2e/functional/tests/e2e.go

new lint errors introduced by #173 showed when ran `make lint` manually not
showing in lint CI run probably an issue in lint CI pipe
```sh
make lint
level=info msg="[config_reader] Config search paths: [./ /app / /root]"
level=info msg="[lintersdb] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]"
level=info msg="[loader] Go packages loading at mode 575 (compiled_files|files|imports|name|types_sizes|deps|exports_file) took 26.006633805s"
level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 7.126455ms"
level=info msg="[linters context/goanalysis] analyzers took 1m25.672392686s with top 10 stages: buildir: 1m9.588045374s, nilness: 3.451406769s, inspect: 2.377262097s, printf: 1.46592711s, fact_purity: …
```

Fix some new lint errors

---

test/e2e/node/node.go

Comment from @msherif1234 that wasn't addressed in #173

E2E test: only pay attention to internal IPs only and explicitly check for ipv6 address

---

pkg/ebpf/ingress_node_firewall_loader.go
pkg/ebpfsyncer/ebpfsyncer.go
test/e2e/functional/tests/e2e.go
test/e2e/ingress-node-firewall/ingress-node-firewall.go

For non existing interfaces we will skip them with an error log in daemon process

Fix #217 apply rules only for valid interface(s) instead of rejecting the whole config

---

bindata/manifests/daemon/daemonset.yaml
controllers/ingressnodefirewallconfig_controller_test.go
hack/kind-cluster.sh
pkg/ebpf/ingress_node_firewall_loader.go
pkg/ebpfsyncer/ebpfsyncer.go

We should mounted bpffs at the host not inside
the pod to be able to presist bpf maps
Fix for OCP will be done via
https://github.com/openshift/machine-config-operator/pull/3386
Note: OCP CI will fail till we have `MCO` PR fixed 

Fix #222 after pod restart bpf maps are gone

---

test/Dockerfile.netcat
test/e2e/functional/tests/e2e.go
test/e2e/images/images.go
test/e2e/node/node.go
test/e2e/transport/transport.go

Tried to find a small netcat image but gave up.
Most were BSD netcat variant and I didnt test with that varient so I stuck with nmaps netcat variant and built our own image.
Removed unused func parameter from func `GetAndEnsureRunningTransportServer` also.
Tested on ipv4 only cluster and KinD.

E2E fixes: switch to smaller image and fix ipv4 only cluster detection

---

hack/kind-cluster.sh

The previous image required isn't cached even if its present in the hosts cache and requires the full 900M download for each cluster installation. Switch to a smaller image.

Fix #227: switch to alpine image for bpf mount daemonset

---

cmd/syslog/syslog.go

to reuse unix socket we have to unlink before attempting to reuse
when the events container restarts
To repro on kind we can restart the node container for example
```sh
docker restart kind-worker
```
from the event container
```
k logs -n ingress-node-firewall-system   ingress-node-firewall-daemon-pkfrd  -c events --previous
2022/10/28 21:19:59 Caught signal terminated: shutting down.
```

OCPBUGS-2934: unlink events unix socket during shutdown

---

bundle.Dockerfile
bundle/manifests/ingress-node-firewall-webhook-service_v1_service.yaml
bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
bundle/manifests/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
bundle/metadata/annotations.yaml
config/crd/kustomization.yaml
config/manifests/kustomization.yaml
config/openshift-olm/namespace.yaml
config/openshift-olm/patch.yaml
config/openshift-olm/rbac.yaml
manifests/stable/ingress-node-firewall-webhook-service_v1_service.yaml
manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
manifests/stable/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml

- we can't use cert-mgr when deploy OLM operator on OCP
- we need to annotate CRD only for raw manifest deploy not for olm bundle deploy
Signed-off-by: msherif1234 <mmahmoud@redhat.com>

Fix #207 to fix TLS errors we need to annotate the CRD

---

Dockerfile.daemon.openshift
Dockerfile.openshift
hack/build-daemon.sh

rhel9 container images causing the following runtime issue causing daemonset crashloop
```shell
/usr/bin/daemon: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /usr/bin/daemon)
/usr/bin/daemon: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/daemon)
```
Signed-off-by: msherif1234 <mmahmoud@redhat.com>

SDN-3721: migrate to rhel9 base images

---

controllers/ingressnodefirewallnodestate_controller.go
pkg/ebpfsyncer/ebpfsyncer.go

when delete daemonSet or daemon pods manually
pods will get recreated but the interface will
have older xdp attached to it
fix an issue where we have stale XDP attached to interface(s) when daemonset restarts
- bring up OCP cluster
- configure sctp and deploy sctp client and server pods
```shell
oc get pods -o wide
NAME         READY   STATUS    RESTARTS   AGE   IP            NODE                                       NOMINATED NODE   READINESS GATES
sctpclient   1/1     Running   0          17s   10.128.2.24   ci-ln-6rzv9ik-72292-ctfxk-worker-c-ls2sf   <none>           <none>
sctpserver   1/1     Running   0          17s   10.129.2.26   ci-ln-6rzv9ik-72292-ctfxk-worker-b-n2x9r   <none>           <none>
```
- configure …

OCPBUGS-11888: handle daemonSet pods restart

---

controllers/ingressnodefirewallnodestate_controller.go
test/e2e/daemonset/daemonset.go
test/e2e/deployment/deployment.go
test/e2e/functional/tests/e2e.go
test/e2e/ingress-node-firewall/ingress-node-firewall.go
test/e2e/namespaces/namespaces.go
test/e2e/pods/pods.go
test/e2e/transport/transport.go

this is follow up to PR #221 
test on kind cluster e2e pass
```shell
make test-e2e
Ran 22 of 22 Specs in 596.378 seconds
SUCCESS! -- 22 Passed | 0 Failed | 0 Pending | 0 Skipped
You're using deprecated Ginkgo functionality
```

SDN-3979: E2E extend testing by including disruption test cases

---

Dockerfile.openshift
bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
manifests/stable/ingress-node-firewall.clusterserviceversion.yaml

Operator Dockerfile incorrectly hardcode arch to amd64
bring up the operator on different arch
fix hardcoded arch `amd64` in the operator dockerfile

OCPBUGS-15828: Fix arm64 arch build images

---

pkg/webhook/webhook.go
pkg/webhook/webhook_suite_test.go
test/e2e/functional/tests/e2e.go

Webhook rules validation should be applied for rules applied to the same
node(s)
I added check o make sure rules validation is done to rules with the same nodeSelector
I extended unit-test to test this case

OCPBUGS-19410: Webhook should validate rules applied to the same node(s)

---

main.go

ingress node firewall operator remediation for CVE-2023-44487

OCPBUGS-21646: Modify controller-runtime to disable HTTP/2 for metrics and webhooks

---

main.go

ingress node firewall operator remediation for CVE-2023-44487

OCPBUGS-20645: Modify controller-runtime to disable HTTP/2 (4.13)

---

bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
config/openshift-olm/kustomization.yaml
manifests/stable/ingress-node-firewall.clusterserviceversion.yaml

update operator image in the csv OCP 4.14

OCPBUGS-22765:replace ingress node firewall container image to match ART's name

---

bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
config/openshift-olm/kustomization.yaml
manifests/stable/ingress-node-firewall.clusterserviceversion.yaml

update operator image in the csv OCP 4.13

OCPBUGS-22766:replace ingress node firewall container image to match ART image

---

bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
manifests/stable/ingress-node-firewall.clusterserviceversion.yaml

update operator image in the csv OCP 4.12

OCPBUGS-22768:replace ingress node firewall container image to match ART

---

Dockerfile
Dockerfile.daemon

update to go1.21 to be able to build upstream with latest cilium package
Error is
```sh
8.579 /go/pkg/mod/github.com/cilium/ebpf@v0.12.2/internal/sysenc/marshal.go:37:29: undefined: unsafe.StringData
8.579 note: module requires Go 1.20
22.46 # sigs.k8s.io/controller-runtime/pkg/cache
```

update golang to 1.21 since cilium latest requires go1.20

---

Dockerfile
api/v1alpha1/ingressnodefirewall_types.go
bundle/manifests/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
config/crd/bases/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
controllers/ingressnodefirewall_controller_rules_test.go
manifests/stable/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
pkg/webhook/webhook_suite_test.go

follow up to #446 PR to update manifests and update unit-test
fixes #444

prevent empty interfaces and configs

---

Dockerfile
Dockerfile.daemon.openshift
Makefile
bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
config/olm-install/install-resources.yaml
manifests/art.yaml
manifests/ingress-node-firewall.package.yaml
manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
openshift-ci/wait_for_csv.sh
pkg/version/version.go

update manifest/bundle and docker files to use 4.16

Update ingress node firewall for 4.16

---

bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
manifests/stable/ingress-node-firewall.clusterserviceversion.yaml

Add `arm64` target to the list of supported architectures

Add arm64 target to CSV

---

.snyk

to avoid unaccurate `SAST` bugs Skip scanning the following:
- vendor folder
- test file
- all the e2e files

Add a .snyk configuration file

---

bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
manifests/stable/ingress-node-firewall.clusterserviceversion.yaml

set infra annotation labels for INFW manifest

OCPBUGS-30561: Set infra labels in ingress-node-firewall-operator

---

manifests/stable/ingress-node-firewall.clusterserviceversion.yaml

iib cannot run when "replaces" specifies a version that's not in the index.
this prevents publishing in ART's internal early-operator index, and also prevents shipping.

OCPBUGS-31636: stable CSV: remove "replaces"

---

pkg/failsaferules/failsaferules.go
pkg/webhook/webhook_suite_test.go

Currently the SSH is protected by failsafe webhook preventing any attempts to configure any rules
for SSH this PR remove SSH from failsafe rules
passed e2e and ut tests
remove SSH from failsafe rules to give user flexibility to configure SSH rules

Users prefer to have flexibility configuring SSH firewall rules

---

.ci-operator.yaml
Dockerfile.daemon.openshift
Dockerfile.openshift
Makefile
bundle.Dockerfile
bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
config/olm-install/install-resources.yaml
go.mod
manifests/art.yaml
manifests/ingress-node-firewall.package.yaml
manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
openshift-ci/ingress-node-firewall-operator-deploy/build_and_push_index.sh
openshift-ci/wait_for_csv.sh
pkg/version/version.go

update ingress node firewall for OCP 4.17 release
update operator sdk

update ingress node firewall with 4.17 base images

---

go.mod

Image build with the following error
`Required/recommended Go toolchain version \'1.22.2\' is not supported yet.`

fix go version to get successfull ART build

---

.ci-operator.yaml
Dockerfile.daemon.openshift
Dockerfile.openshift
go.mod

bump golang to go1.22
this PR includes #525 & #524

Bump golang to go1.22

---

openshift-ci/deploy_ingress_node_firewall.sh

error: exec [POD] [COMMAND] is not supported anymore. Use exec [POD] -- [COMMAND] instead

fix ci run errors

---

Dockerfile
Dockerfile.daemon
Makefile
bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
config/olm-install/install-resources.yaml
manifests/art.yaml
manifests/ingress-node-firewall.package.yaml
manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
openshift-ci/wait_for_csv.sh
pkg/version/version.go

Update ingress node firewall for OCP release 4.19

update INFW for OCP 4.19 release

---

go.mod
go.sum
vendor/github.com/golang/glog/glog_file.go
vendor/modules.txt

#605  
This PR updates the glog package to v1.2.4 to fix a vulnerability in the previous version

[Release-4.18] OCPBUGS-58581: Bump github.com/golang/glog from 1.2.3 to 1.2.4 

---

openshift-ci/ingress-node-firewall-operator-deploy/build_and_push_index.sh

Fix a PROW job failure in 4.16 caused by misconfiguration in extracting the pull secret/password.
Tracker : https://issues.redhat.com/browse/OCPBUGS-59926

OCPBUGS-59926: fix-ingress-node-firewall-e2e-metal-ipi
